language: python
install:
- pip install pytest
- pip install geojson
- pip install forked-path
- npm install -g geojson-merge
before_script:
- echo "about to deploy..."
- git config user.name "brianamarie"
- git config user.email "brianamarie@github.com"
- git pull
- mv class-pins.topojson class-pins
- geojson-merge *.topojson class-pins > class-pins.topojson
- rm class-pins
- mv class-pins.topojson class-pins
- rm *.topojson
- mv class-pins class-pins.topojson
- git add .
- git commit -m 'using travis to merge files'
- git tag -a v2.8-lw -m "message"
script: py.test
deploy:
  provider: releases
  api_key:
    secure: dqQDw96I6ZHfQyG+Cgz8QEj+YZNtk3E6l6ztwFtxEuujO+u1A2hlmHNjxAeJTCAqi9seKKwCnEHBojO2/TTB94QRh6Sr9w4v5zUMeA1uq7nfpeppo8y2Z3+hao7EPfw3D75sctnNXuTl6kIp79qAst3k4UpuPU6uH2qVHwAQoDKM9UT4Wte6NVEzgQTKuF/vycwdOyw3aYa8tV2ks/+o2HvqiWaajv3P6fhDUEIS7lrEGM3eOodG0Aos8uZqYyK/nEL/EyS0vMFOiHadqv/xT0Na2rnEwIw3Er9LoYe+EPv8Qv5vJRMQIl4Jz2i+lw20yvT1HFesiVwusd8GjnPCjXt7+TvBeJbz/fu//0f6ve+E5+EvXpwQNMVLxilrw4hItP8YQnqjUaHLC5+PFTz9iHMmwTmjbVHbQlHzMrF7n/V3emXkXHtrt7ahKY4IHB+7l5W+p5kdrd9fBfTiT6tZ23IF9qPKiwsG7ZJjE7a/bmrRfndsf+DQl6Mtub9CCgSWcRwQzpTukH5+f1DVEotv40oqh41uL0hwvTST42hkZHtFXEJNOrfch+IstFlgFGZ+0d11hbo5bEsNumvxHcL0l/XVQeu44eiwlwBqgag/VN9HXuPsswmzjFBxRFkLwdgvYJvkOHOwGAF6yB2TOD9EmbdLjGYzL3tzMMouDXmeNnc=
  file: 'class-pins.topojson'
  on:
    repo: brianamarie/travel-log
    tags: true
  skip_cleanup: true
  overwrite: true
before_install:
- openssl aes-256-cbc -K $encrypted_4f8e0108f7a1_key -iv $encrypted_4f8e0108f7a1_iv
  -in deploy-key.enc -out deploy-key -d
